version: '3'
services:
  jenkins:
    build:
      context: ./
    container_name: jenkins
    environment:
      JAVA_OPTS: "-Xmx512m -Xms512m"
      #JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - '8080:8080'
      - '5000:5000'
    volumes:
      # mkdir -p ./data/jenkins_home ./data/ansible && chmod 775 ./data/jenkins_home && umask 0002
      - ./data/jenkins_home:/var/jenkins_home
      - ./data/ansible:/etc/ansible
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
